ans<-fread("submission_ans.csv")
ans_min<-fread("submission_min.csv")
ans_max<-fread("submission_max.csv")
ans_mean<-fread("submission_mean.csv")
ans_meddian<-fread("submission_meddian.csv")
ans_005<-fread("submission_005.csv")
ans_01<-fread("submission_01.csv")
ans_001<-fread("submission_001.csv")
ans_0025<-fread("submission_0025.csv")
ans_003<-fread("submission_003.csv")
ans_002<-fread("submission_002.csv")
ans_cross<-fread("submission_cross.csv")

ans<-ans%>%mutate(target= ifelse(target >= 0.5, 1, 0 ))

calc_auc<-function(ans_){
  pred <- prediction(ans_$target, ans$target)
  auc.tmp <- performance(pred,"auc")
  auc <- as.numeric(auc.tmp@y.values)
  print(auc)
}
calc_auc(ans_min)
calc_auc(ans_max)
calc_auc(ans_mean)
calc_auc(ans_meddian)
calc_auc(ans_005)
calc_auc(ans_01)
calc_auc(ans_001)
calc_auc(ans_0025)
calc_auc(ans_003)
calc_auc(ans_002)
calc_auc(ans_cross)
